site_name: Vue.js Studies
repo_url: https://github.com/jbcodeforce/vuejs-studies.git
nav:
  - Introduction: index.md
  - Vuetify: vuetify.md

theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences